///////////////////////////////////
// !!! DO NOT EDIT THIS FILE !!! //
///////////////////////////////////

import { SlackAPIResponse } from "../response";
export type AdminConversationsSetConversationPrefsResponse =
  SlackAPIResponse & {
    error?: string;
    needed?: string;
    ok: boolean;
    provided?: string;
  };
