///////////////////////////////////
// !!! DO NOT EDIT THIS FILE !!! //
///////////////////////////////////

import { SlackAPIResponse } from "../response";
export type AdminInviteRequestsApprovedListResponse = SlackAPIResponse & {
  approved_requests?: string[];
  error?: string;
  needed?: string;
  ok: boolean;
  provided?: string;
};
