///////////////////////////////////
// !!! DO NOT EDIT THIS FILE !!! //
///////////////////////////////////

import { SlackAPIResponse } from "../response";
export type AdminTeamsOwnersListResponse = SlackAPIResponse & {
  error?: string;
  needed?: string;
  ok: boolean;
  owner_ids?: string[];
  provided?: string;
  response_metadata?: ResponseMetadata;
};

export interface ResponseMetadata {
  next_cursor?: string;
}
