///////////////////////////////////
// !!! DO NOT EDIT THIS FILE !!! //
///////////////////////////////////

import { SlackAPIResponse } from "../response";
export type ChatPostEphemeralResponse = SlackAPIResponse & {
  error?: string;
  message_ts?: string;
  needed?: string;
  ok: boolean;
  provided?: string;
};
