///////////////////////////////////
// !!! DO NOT EDIT THIS FILE !!! //
///////////////////////////////////

import { SlackAPIResponse } from "../response";
export type FilesCommentsEditResponse = SlackAPIResponse & {
  comment?: Comment;
  error?: string;
  needed?: string;
  ok: boolean;
  provided?: string;
};

export interface Comment {
  comment?: string;
  created?: number;
  id?: string;
  is_intro?: boolean;
  timestamp?: number;
  user?: string;
}
