///////////////////////////////////
// !!! DO NOT EDIT THIS FILE !!! //
///////////////////////////////////

import { SlackAPIResponse } from "../response";
export type RtmConnectResponse = SlackAPIResponse & {
  error?: string;
  needed?: string;
  ok: boolean;
  provided?: string;
  self?: Self;
  team?: Team;
  url?: string;
};

export interface Self {
  id?: string;
  name?: string;
}

export interface Team {
  domain?: string;
  id?: string;
  name?: string;
}
